# Generated by Django 2.0.6 on 2018-07-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('board_name', models.CharField(max_length=255)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
