# Generated by Django 2.0.6 on 2018-07-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=models.SET('Board deleted'), related_name='history', to='boards.Board')),
            ],
        ),
    ]
